# Generated by Django 4.1.7 on 2023-07-23 14:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('nip', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('petugas_monitor', 'Petugas Monitor'), ('petugas_agenda', 'Petugas Agenda')], max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
    ]
