# Generated by Django 4.1.7 on 2023-07-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('nip', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('petugas_monitor', 'Petugas Monitor'), ('petugas_input_agenda_setting', 'Petugas Input Agenda Setting')], max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
