# Generated by Django 4.1.7 on 2023-08-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityChecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ue1', models.CharField(choices=[('All', 'All'), ('Kemenkeu', 'Kemenkeu'), ('Setjen', 'Setjen'), ('DJA', 'DJA'), ('DJP', 'DJP'), ('DJPPR', 'DJPPR'), ('DJPB', 'DJPB'), ('DJKN', 'DJKN'), ('DJBK', 'DJBK'), ('Itjen', 'Itjen'), ('DJBC', 'DJBC'), ('BKF', 'BKF'), ('BPPK', 'BPPK'), ('SMV', 'SMV')], max_length=255)),
                ('social_media', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Linkedin', 'Linkedin'), ('Tiktok', 'Tiktok'), ('Twitter', 'Twitter'), ('YouTube', 'YouTube')], max_length=20)),
                ('account_url', models.URLField()),
                ('post_url', models.URLField()),
                ('captions', models.TextField()),
                ('topik', models.CharField(max_length=255)),
                ('pesan_kunci', models.CharField(max_length=255)),
                ('sub_pesan_kunci', models.CharField(max_length=255)),
                ('kesesuaian', models.CharField(choices=[('Sesuai', 'Sesuai'), ('Tidak Sesuai', 'Tidak Sesuai')], max_length=50)),
                ('catatan', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
