# Generated by Django 4.1.7 on 2023-08-01 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('input_agenda_setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='InstagramCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True)),
                ('posted_date_time', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='similarity_checker.instagramaccount')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input_agenda_setting.inputagendasetting')),
            ],
        ),
    ]
