# Generated by Django 4.1.7 on 2023-08-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similarity_checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similaritychecker',
            name='ue1',
            field=models.CharField(choices=[('Kemenkeu', 'Kemenkeu'), ('Setjen', 'Setjen'), ('DJA', 'DJA'), ('DJP', 'DJP'), ('DJPPR', 'DJPPR'), ('DJPB', 'DJPB'), ('DJKN', 'DJKN'), ('DJBK', 'DJBK'), ('Itjen', 'Itjen'), ('DJBC', 'DJBC'), ('BKF', 'BKF'), ('BPPK', 'BPPK'), ('SMV', 'SMV')], max_length=255),
        ),
    ]
