# Generated by Django 4.1.7 on 2023-08-01 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocmedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ue1', models.CharField(choices=[('All', 'All'), ('Kemenkeu', 'Kemenkeu'), ('Setjen', 'Setjen'), ('DJA', 'DJA'), ('DJP', 'DJP'), ('DJPPR', 'DJPPR'), ('DJPB', 'DJPB'), ('DJKN', 'DJKN'), ('DJBK', 'DJBK'), ('Itjen', 'Itjen'), ('DJBC', 'DJBC'), ('BKF', 'BKF'), ('BPPK', 'BPPK'), ('SMV', 'SMV')], max_length=255)),
                ('account_url', models.URLField()),
                ('date_time', models.DateTimeField()),
                ('text_captions', models.TextField()),
                ('likes', models.PositiveIntegerField()),
                ('comments', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('socmeddata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socmed_data.socmeddata')),
            ],
            bases=('socmed_data.socmeddata',),
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('socmeddata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socmed_data.socmeddata')),
            ],
            bases=('socmed_data.socmeddata',),
        ),
        migrations.CreateModel(
            name='Linkedin',
            fields=[
                ('socmeddata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socmed_data.socmeddata')),
            ],
            bases=('socmed_data.socmeddata',),
        ),
        migrations.CreateModel(
            name='Tiktok',
            fields=[
                ('socmeddata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socmed_data.socmeddata')),
            ],
            bases=('socmed_data.socmeddata',),
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('socmeddata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socmed_data.socmeddata')),
            ],
            bases=('socmed_data.socmeddata',),
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('socmeddata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socmed_data.socmeddata')),
            ],
            bases=('socmed_data.socmeddata',),
        ),
    ]
