# Generated by Django 4.1.7 on 2023-08-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_url', models.URLField()),
                ('social_media', models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Linkedin', 'Linkedin'), ('Tiktok', 'Tiktok'), ('Twitter', 'Twitter'), ('YouTube', 'YouTube')], max_length=20)),
                ('ue1', models.CharField(choices=[('Kemenkeu', 'Kemenkeu'), ('Setjen', 'Setjen'), ('DJA', 'DJA'), ('DJP', 'DJP'), ('DJPPR', 'DJPPR'), ('DJPB', 'DJPB'), ('DJKN', 'DJKN'), ('DJBK', 'DJBK'), ('Itjen', 'Itjen'), ('DJBC', 'DJBC'), ('BKF', 'BKF'), ('BPPK', 'BPPK'), ('SMV', 'SMV')], max_length=50)),
            ],
        ),
    ]
