# Generated by Django 4.1.7 on 2023-08-05 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socmed_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediadata',
            name='captions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediadata',
            name='comments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediadata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='socialmediadata',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediadata',
            name='viewers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
