# Generated by Django 4.1.7 on 2023-08-01 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socmed_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socmeddata',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='socmeddata',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='socmeddata',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='socmeddata',
            name='text_captions',
        ),
    ]
