# Generated by Django 4.1.7 on 2023-08-01 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input_agenda_setting', '0001_initial'),
        ('socmed_data', '0002_remove_socmeddata_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socmeddata',
            name='input_agenda_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='input_agenda_setting.inputagendasetting'),
        ),
    ]
