# Generated by Django 4.1.7 on 2023-08-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socmed_data', '0003_linkedinpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediadata',
            name='followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediadata',
            name='post_urls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediadata',
            name='posts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
