# Generated by Django 4.1.7 on 2023-08-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socmed_data', '0004_socialmediadata_followers_socialmediadata_post_urls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediadata',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediadata',
            name='likes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediadata',
            name='viewers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
