# Generated by Django 4.1.7 on 2023-08-05 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('input_agenda_setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputagendasetting',
            name='agenda_date_time_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
